version: '3'

services:
  redis:
    image: redis:4
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - 6479:6379
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
    networks:
      - code-network

  mariadb:
    image: mariadb/server:10.3
    restart: always
    container_name: mariadb
    hostname: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: brainlabs
      MARIADB_ROOT_HOST: "%"
      MARIADB_USER: admin
      MARIADB_PASSWORD: brainlabs
      TZ: "Asia/Jakarta"
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - code-network

  elastic:
     image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
     container_name: elastic
     restart: always
     hostname: elastic
     environment:
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       - "discovery.type=single-node"
     ports:
       - 9300:9200
     ulimits:
       memlock:
         soft: -1
         hard: -1
     networks:
       - code-network
     volumes:
       - elastic:/usr/share/elasticsearch/data
     depends_on:
       - mariadb

  kibana:
     image: docker.elastic.co/kibana/kibana:6.6.2
     container_name: kibana
     hostname: kibana
     restart: always
     environment:
       ELASTICSEARCH_HOSTS: http://elastic:9200
       ELASTICSEARCH_URL: http://elastic:9200
       SERVER_NAME: kibana.local
     depends_on:
       - mariadb
       - elastic
     networks:
       - code-network
     ports:
       - 5601:5601
  rll-url-shortener:
    build:
      context: .
      dockerfile: deployment/dockerfiles/dockerfile-local
    working_dir: /go/src/github.com/ralali/rll-url-shortener
    container_name: rll-url-shortener
    hostname: rll-url-shortener
    networks:
      - code-network
    volumes:
      - .:/go/src/github.com/ralali/rll-url-shortener
    ports:
      - 8081:8081
    depends_on:
      - mariadb
      - redis

volumes:
  elastic:
    driver: local
  mariadb:
    driver: local

networks:
  code-network:
    driver: bridge